In [89]:
import numpy as np


In [90]:
A = np.array([0.2, 0.4, 0.6, 0.8]) # Fuzzy set A
B = np.array([0.3, 0.5, 0.7, 0.9])# Fuzzy set B

In [91]:
# Function to perform Union operation on fuzzy sets
def fuzzy_union(A, B): 
    return np.maximum(A, B)
union_result = fuzzy_union(A, B)
print("Union:", union_result)


Union: [0.3 0.5 0.7 0.9]


In [92]:
# Function to perform Intersection operation on fuzzy sets
def fuzzy_intersection(A, B):
    return np.minimum(A, B)
intersection_result = fuzzy_intersection(A, B)
print("Intersection:", intersection_result)


Intersection: [0.2 0.4 0.6 0.8]


In [93]:
# Function to perform Complement operation on a fuzzy set
def fuzzy_complement(A): 
    return 1 - A
complement_A = fuzzy_complement(A)
print("Complement of A:", complement_A)

Complement of A: [0.8 0.6 0.4 0.2]


In [94]:
# Function to perform Difference operation on fuzzy sets
def fuzzy_difference(A, B): 
    return np.minimum(A, 1 - B)
difference_result = fuzzy_difference(A, B)
print("Difference:", difference_result)

Difference: [0.2 0.4 0.3 0.1]


In [95]:
# Function to create fuzzy relation by Cartesian product of two fuzzy sets
def cartesian_product(A, B): 
    return np.outer(A, B)


In [ ]:
def max_min_composition(R, S):
    result = np.zeros((R.shape[0], S.shape[1]))
    
    for i in range(R.shape[0]):        # iterate rows of R
        for j in range(S.shape[1]):    # iterate columns of S
            result[i][j] = np.max(
                np.minimum(R[i, :], S[:, j])
            )
    
    return result

In [96]:
# Fuzzy relations using Cartesian product
R_rel = cartesian_product(A, B)
S_rel = cartesian_product(B, A)

# Max-Min composition
composition_result = max_min_composition(R_rel, S_rel)

print("Cartesian product of R (A×B):")
print(R_rel)

print("\nCartesian product of S (B×A):")
print(S_rel)

print("\nMax-Min composition:")
print(composition_result)

Cartesian product of R (A×B):
[[0.06 0.1  0.14 0.18]
 [0.12 0.2  0.28 0.36]
 [0.18 0.3  0.42 0.54]
 [0.24 0.4  0.56 0.72]]

Cartesian product of S (B×A):
[[0.06 0.12 0.18 0.24]
 [0.1  0.2  0.3  0.4 ]
 [0.14 0.28 0.42 0.56]
 [0.18 0.36 0.54 0.72]]

Max-Min composition:
[[0.18 0.18 0.18 0.18]
 [0.18 0.36 0.36 0.36]
 [0.18 0.36 0.54 0.54]
 [0.18 0.36 0.54 0.72]]
